### PR TITLE
fixed typo

### PR DESCRIPTION
**Pull request by Logan1x**
Fixed typo in readme.md

### CODE REVIEW

**Comment by Logan1x** [comment]
@xeon-zolt  I liked the project and would love to know more about this project, How can I help.

**Comment by xeon-zolt** [comment]
@Logan1x currently we are making maps for package managers for apt so that it works perfectly on Meilix later we plan to map for other package managers you can start by making maps as described in readme or creating Travis CI test cases or packing it up to Debian package for GitHub releases or if you have a better solution for the problem you can share it.

**Comment by Logan1x** [comment]
what does "making maps" means?

**Comment by xeon-zolt** [comment]
check data folder for maps

**Comment by Logan1x** [comment]
selection_007
I am getting this error while cloning it locally can you help?

**Comment by xeon-zolt** [comment]
so we need to add checks here if no argument is passed

**Comment by Logan1x** [comment]
So you should make issue

**Comment by Logan1x** [comment]
@xeon-zolt @gabru-md can you help me in [this](https://github.com/fossasia/mew/pull/18#issuecomment-361524258)?

**Pull request merged**
