### PR TITLE
Mew Deb package creation

### PR DESCRIPTION
**Pull request by xeon-zolt**
added a script to generate deb package to be installed in Meilix without the need to rebuilding while building Meilix 
todo 
- [x] create deb package from ubuntu folder
- [ ]  deploy the package to a repo for meilix

### CODE REVIEW

**Comment by abishekvashok** [comment]
Which repo for deployment?

**Comment by xeon-zolt** [comment]
meilix ppa

**Comment by abishekvashok** [comment]
Place it in the root of the meilix repo, then run, `reprepro includedeb trusty ./nameOfYourMeta-package.deb` and commit. When your pr is merged and Travis runs on the merge commit, the apt-bot will add it to our ppa.

**Comment by abishekvashok** [comment]
That should be done in meilix repo and not here.

**Comment by meets2tarun** [comment]
@xeon-zolt 
Do we need this PR? or close it

**Pull request closed without merging**
